### ISSUE TITLE
error when installing on windows server 2019

### ISSUE THREAD

**Issue by TrueGodOfHyperdeath** [DanATW/numberize#7]
when installing via `pip install numberize` gives 
`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\ \HostX86\\x64\\cl.exe' failed with exit code 2
`

**Comment by yemchenko-dan** [comment]
Is it a full trace?
Could you provide a version of your python interpreter and pip?

**Comment by TrueGodOfHyperdeath** [comment]
the error appears when installing the DAWG library. This is a common mistake for them. i use python 3.10 and pip 23.0.1

**Comment by yemchenko-dan** [comment]
It seems, that their repo is not maintained. There is a [PR](https://github.com/pytries/DAWG/pull/50), that adds python 3.10 support, but it is not merged.
I think we can just remove this library from dependencies, and use simple dicts.

**Comment by TrueGodOfHyperdeath** [comment]
this would be handy. Thank you

**Comment by yemchenko-dan** [comment]
@TrueGodOfHyperdeath Try installing numberize now. Use 1.1.2 version. Ping me with results, please.

**Comment by TrueGodOfHyperdeath** [comment]
@yemchenko-dan Thank you. Everything worked out

**Comment by yemchenko-dan** [comment]
@TrueGodOfHyperdeath Cool.

It should be compatible with python 3.11 btw.
